# Generated by Django 5.1.6 on 2025-03-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_limitorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitorder',
            name='created_at',
        ),
    ]
