# Generated by Django 5.1.6 on 2025-03-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_limitorder_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-10-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-10-01 00:00:00'),
            preserve_default=False,
        ),
    ]
