# Generated by Django 5.1.6 on 2025-03-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_limitorder_created_at_userstock_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstock',
            name='order_type',
            field=models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit')], default='MARKET', max_length=6),
        ),
    ]
