# Generated by Django 5.1.6 on 2025-03-18 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
