# Generated by Django 5.1.6 on 2025-03-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_realized_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
