# Generated by Django 5.1.6 on 2025-03-28 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_userprofile_total_realized_profit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='total_realized_profit',
            new_name='cumulative_profit',
        ),
    ]
