"""
Django settings for stockproject project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import dj_database_url

import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"


ALLOWED_HOSTS = [
    ".up.railway.app",
]



# ALLOWED_HOSTS = [
#     "52.172.222.95",
#     "20.193.151.222",  # Your Azure VM IP
#     "localhost",
#     "127.0.0.1",
#     # Add your domain if you have one
# ]

# Application definition

INSTALLED_APPS = [
    'corsheaders',  # Must be before any middleware-dependent apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',  # Required for sessions
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mainapp',
    'django_celery_results', 
    'django_celery_beat',
    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Should be just after SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # Keep this enabled
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
import datetime

JWT_SECRET_KEY = os.environ.get("JWT_SECRET_KEY")  # Use env variable in production!
JWT_ALGORITHM = 'HS256'
JWT_EXP_DELTA_SECONDS = 36000  # 10 hour token validity , 36000 seconds = 10 hours

# Security Settings
# CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SECURE = True
# CSRF_COOKIE_SAMESITE = 'None'
# CSRF_COOKIE_DOMAIN = None  # Remove the IP address, let Django handle it
# CSRF_USE_SESSIONS = False  # Not True, as you're using cookies

# CORS Settings
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.vercel\.app$",
    r"^http://localhost:3000$",
]


SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = True



MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


CORS_ALLOW_CREDENTIALS = True  # Allow cookies for authentication
CSRF_TRUSTED_ORIGIN_REGEXES = [
    r"^https://.*\.vercel\.app$",
]



# CORS_EXPOSE_HEADERS = ['X-CSRFToken'] 

# Session Settings
# SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = True
# SESSION_COOKIE_HTTPONLY = True
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stockproject.wsgi.application'
ASGI_APPLICATION = 'stockproject.asgi.application'

ROOT_URLCONF = "stockproject.urls"
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.parse(
        os.getenv("DATABASE_URL"),
        conn_max_age=600,
        ssl_require=True,
    )
}
print("DATABASE_URL =", os.environ.get("DATABASE_URL"))


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]
# If using Django Channels
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
import os

STATIC_URL = '/static/'

# Add frontend's build folder to static files
FRONTEND_DIST_DIR = os.path.join(BASE_DIR, "frontend", "dist")

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),  # Global static files
    os.path.join(BASE_DIR, "mainapp", "static"),  # App-specific static files
    FRONTEND_DIST_DIR,  # React build folder
]

# Directory where static files will be collected in production
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




# # celery settings
# CELERY_BROKER_URL = 'redis://127.0.0.1:6379'
# accept_content= ['application/json'] 
# result_serializer = 'json'
# task_serializer = 'json'
# timezone = 'Asia/Kolkata'
# result_backend = 'django-db'# at which place the result will be stored 

# broker_connection_retry_on_startup = True

# CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             "hosts": [('127.0.0.1', 6379)],
#         },
#     },
# }

from decouple import config

# Email settings
# EMAIL_BACKEND = config('EMAIL_BACKEND')
# EMAIL_HOST = config('EMAIL_HOST')
# EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
# EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS") == "True"
# EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL") == "True"

# EMAIL_HOST_USER = config('EMAIL_HOST_USER')
# EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
# DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL")
SENDGRID_API_KEY = os.environ.get("SENDGRID_API_KEY")
print("SENDGRID_API_KEY exists:", bool(SENDGRID_API_KEY))
print("DEFAULT_FROM_EMAIL:", DEFAULT_FROM_EMAIL)

REDIS_URL = os.getenv("REDIS_URL")
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}




# Celery
CELERY_BROKER_URL = REDIS_URL

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Asia/Kolkata"

CELERY_RESULT_BACKEND = "django-db"
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
broker_connection_retry_on_startup = True

# Channels
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
        },
    },
}


